services:
  - type: web
    name: pointcalculator-api
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: pointcalculator.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://esal-57.github.io
      - key: RIOT_REGION
        value: asia
      - key: RIOT_PLATFORM
        value: kr
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: RIOT_API_KEY
        sync: false
